
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.79.175.205/adshare?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:

      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: on
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: on

      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: on
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500



  mail:
    host: smtp.qq.com
    username: 3596405356@qq.com
    password: edwsruruoymddacd
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  messages:
    basename: i18n.login,i18n.register
  mvc:
    date-format: yyyy-MM-dd



server:
  servlet:
    context-path: /adshare
  port: 8088

mail:
  mailFrom: 3596405356@qq.com
  domainName: http://120.79.175.205:8088/adshare

#debug: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
